
CREATE TABLE AUTHOR( ID int AUTO_INCREMENT PRIMARY KEY NOT NULL , NAME char(20), FIRSTNAME char(20), BIRTHDATE DATE);

CREATE TABLE BOOK( ID int AUTO_INCREMENT PRIMARY KEY NOT NULL , TITLE char(50) UNIQUE, PRICE float,FK_AUTHOR_ID int, FOREIGN KEY (FK_AUTHOR_ID) REFERENCES AUTHOR(ID));