-- DROP TABLE IF EXISTS BOOK;

-- DROP TABLE IF EXISTS AUTHOR;

-- CREATE TABLE AUTHOR( AUTHOR_ID int AUTO_INCREMENT PRIMARY KEY NOT NULL , NAME char(20), FIRSTNAME char(20), BIRTHDATE DATE);

-- CREATE TABLE BOOK( BOOK_ID int AUTO_INCREMENT PRIMARY KEY NOT NULL , TITLE char(50) UNIQUE, PRICE float, FOREIGN KEY (FK_AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID));


INSERT INTO AUTHOR (ID,NAME,FIRSTNAME, BIRTHDATE) VALUES (1,'Zola','Emile',{ts '1840-04-02 00:00:00.0'});
INSERT INTO AUTHOR (ID,NAME,FIRSTNAME, BIRTHDATE) VALUES (2,'Hugo','Victor',{ts '1802-05-22 00:00:00.0'});

INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (1,'Contes à Ninon',19,1);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (2,'La Confession de Claude',15,1);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (3,'Villégiature',80,1);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (4,'L''Attaque du Moulin',5,1);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (5,'Les Mystères de Marseille',12,1);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (6,'Le Voeu d''une morte',25,1);

INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (7,'Bug-Jargal',5,2);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (8,'Han d''Islande',10,2);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (9,'Le Dernier Jour d''un condamné',10,2);
INSERT INTO BOOK (ID, TITLE, PRICE, FK_AUTHOR_ID)VALUES (10,'Notre-Dame de Paris',30,2);